name: Tests

on: pull_request

jobs:
  rspec:
    name: rspec tests
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.2
        bundler-cache: true

    - name: Run rspec tests
      run: |
        bundle exec rspec


    - name: Upload coverage results
      uses: actions/upload-artifact@v3
      with:
        include-hidden-files: 'true'
        name: coverage-results
        path: coverage
        retention-days: 5

  coverage:
    needs: rspec
    runs-on: ubuntu-latest
    steps:
      - name: Coverage report
        uses: k1LoW/octocov-action@1ad702b3118b6a055c00b01db68ca0d9f6641dbc # v1.4.0
        with:
          config: .octocov.yml
